version: '3.7'

services:
  localstack:
    image: localstack/localstack
    environment:
      - DATA_DIR=/tmp/localstack/data
      - SERVICES=lambda,sns,sqs,stepfunctions,apigateway
      - LAMBDA_EXECUTOR=docker
    ports:
      - '4566:4566'
    volumes:
      - /tmp/localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  wiremock:
    image: rodolpheche/wiremock
    container_name: wiremock
    volumes:
      - ./__files:/home/wiremock/__files
      - ./mappings:/home/wiremock/mappings
    ports:
      - 8080:8080